kind: pipeline
type: docker
name: default

steps:
  - name: linter
    image: golangci/golangci-lint:latest
    pull: always
    commands:
      - golangci-lint run -v

  - name: test
    image: golang:1.17
    commands:
      - go test ./...
    depends_on: [ linter ]

  - name: build
    image: golang:1.17
    commands:
      - CGO_ENABLED=0 go build ./cmd/cow
    depends_on: [ test ]

  - name: publish_docker
    image: plugins/docker
    pull: always
    settings:
      repo: romaspirin/cow-backend
      registry: hub.docker.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    depends_on: [ build ]
