version: "3.8"

services:
  tarantool:
    image: romaspirin/tnt-cow:simple
    ports:
      - "3301:3301"
    container_name: tnt-cow
    environment:
      - TARANTOOL_USER_NAME=tarantool
      - TARANTOOL_USER_PASSWORD=tarantool
